export const cageQuotes = [
    `I think I jump around more when I'm alone.`,
    `It's a family that's loaded with grudges and passion. We come from a long line of robbers and highwaymen in Italy, you know. Killers, even.`,
    `Sometimes people think I'm wearing a wig when I'm not wearing a wig, and then sometimes they think I'm not wearing a wig when I am wearing a wig.`,
    `I am not a demon. I am a lizard, a shark, a heat-seeking panther. I want to be Bob Denver on acid playing the accordion.`,
    `I don't drink blood, and last time I looked in the mirror, I had a reflection.`,
    `I'm not afraid to play ugly - look at 'Adaptation.' I looked like a turd that a cat had coughed up.`,
    `I'm sticking my tongue out in scenes to try to make that work in 3D. I'm thinking I'll try to get my tongue all the way out to the second row of the audience.`,
    `I'm going to steal the Declaration of Independence.`,
    `Put... the bunny... back... in the box.`,
    `You'll be seeing a lot of changes around here. Papa's got a brand new bag.`,
    `Tool up, honey bunny. It's time to get bad guys.`,
    `What did I do? You fuck with the bull, you get the horns. That's what I did.`,
    `I'll be taking these Huggies and whatever cash ya got.`,
    `I did a bare ass 360 triple back flip in front of twenty two thousand people. It's kind of funny, it's on Youtube, check it out. But when my dad got sick, I did something way crazier than that.`];